install-job:
  stage: build
  tags:
    - python
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip freeze
    - deactivate
  artifacts:
    expire_in: '60'
    paths:
      - venv

initialize-job:
  stage: test
  tags:
    - python
  script:
    - source venv/bin/activate
    - echo "DJANGO_SUPERUSER_USERNAME=TEST" >> secret.env
    - echo "DJANGO_SUPERUSER_PASSWORD=TEST" >> secret.env
    - echo "DJANGO_SUPERUSER_EMAIL=TEST@example.com" >> secret.env
    - python3 src/manage.py createsuperuser
    - python3 src/manage.py migrate
    - deactivate
  artifacts:
    expire_in: '60'
    paths:
      - secret.env
      - src/*.sqlite3

deploy-prod:
  stage: deploy
  tags:
    - python
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production