install-job:
  stage: build
  environment: development
  tags:
    - python
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip freeze
    - deactivate
  artifacts:
    expire_in: '60'
    paths:
      - venv

initialize-job:
  stage: test
  environment: development
  tags:
    - python
  script:
    - source venv/bin/activate
    - echo "DJANGO_SUPERUSER_USERNAME=TEST" >> secret.env
    - echo "DJANGO_SUPERUSER_PASSWORD=TEST" >> secret.env
    - echo "DJANGO_SUPERUSER_EMAIL=TEST@example.com" >> secret.env
    - python3 src/manage.py createsuperuser
    - python3 src/manage.py migrate
    - deactivate
    - rm -rf venv
  artifacts:
    expire_in: 1 week
    paths:
      - secret.env
      - src/*.sqlite3

release-to-github:
  stage: release
  environment: production
  tags:
    - python
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo 'echo $GH_SSH_PASSPHRASE' > ~/.ssh/tmp && chmod 700 ~/.ssh/tmp
    - echo "$GH_SSH_PK_BASE64" | base64 -d | DISPLAY=None SSH_ASKPASS=~/.ssh/tmp ssh-add -
    - ssh-keyscan github.com >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "affenmilchmann@gmail.com"
    - git config --global user.name "Elen Kartina"
    - git push git@github.com:afmigoo/fsthub.git main
