name: FSThub CI
run-name: ${{ gitea.actor }} is running FSThub CI
on: [push]

defaults:
  run:
    shell: bash

jobs:
  testing:
    name: Test the development app
    runs-on: ubuntu-latest
    container: gitea.local:3003/elenkart/pyrunner:ubuntu-22.04-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install HFST
        run: |
          apt update && apt upgrade -y
          apt install -y hfst
      - name: Install python dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip freeze
      - name: Run tests
        run: |
          echo "Activating environment"
          source venv/bin/activate
          echo "Running tests"
          python3 fsthub/manage.py test fsthub --verbosity=2 --no-input || \
          { echo "Tests failed"; exit 1; }

  deploy-to-prod:
    name: Deploy to production
    needs: [testing]
    runs-on: ubuntu-latest
    container: gitea.local:3003/elenkart/pyrunner:ubuntu-22.04-slim
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
            ssh-private-key: ${{ secrets.FSTHUB_SSH_PK }}
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.FSTHUB_SSH_PORT }} lingconlab.ru >> ~/.ssh/known_hosts
      - name: Pull from Github
        run: ssh ${{ secrets.FSTHUB_SSH_USER }}@lingconlab.ru -p ${{ secrets.FSTHUB_SSH_PORT }} \
             "cd production && git pull"
      - name: Restart container
        run: ssh ${{ secrets.FSTHUB_SSH_USER }}@lingconlab.ru -p ${{ secrets.FSTHUB_SSH_PORT }} \
             "cd production && docker compose stop && docker compose up --build -d"
      - name: Make migrations
        run: ssh ${{ secrets.FSTHUB_SSH_USER }}@lingconlab.ru -p ${{ secrets.FSTHUB_SSH_PORT }} \
             "cd production && docker compose exec app /bin/bash -c \"python3 manage.py migrate --noinput\""
      - name: Collect static
        run: ssh ${{ secrets.FSTHUB_SSH_USER }}@lingconlab.ru -p ${{ secrets.FSTHUB_SSH_PORT }} \
             "cd production && docker compose exec app /bin/bash -c \"python3 manage.py collectstatic --noinput\""
