# Generated by Django 5.2.1 on 2025-06-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FstType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('directory', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FstTypeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fst_file', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fsttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fst_file',), name='unique_project_file')],
            },
        ),
    ]
