# Generated by Django 5.2.1 on 2025-06-20 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FstLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FstLanguageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fst_file', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='fsttyperelation',
            name='unique_project_file',
        ),
        migrations.AlterField(
            model_name='fsttype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='fsttyperelation',
            constraint=models.UniqueConstraint(fields=('fst_file',), name='unique_project_file_for_type'),
        ),
        migrations.AddField(
            model_name='fstlanguagerelation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fsttype'),
        ),
        migrations.AddConstraint(
            model_name='fstlanguagerelation',
            constraint=models.UniqueConstraint(fields=('fst_file',), name='unique_project_file_for_language'),
        ),
    ]
