# Generated by Django 5.2.1 on 2025-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fstproject_author_alter_fstproject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fstfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
