# Generated by Django 5.2.1 on 2025-06-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fstlanguagerelation_language'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fstlanguagerelation',
            name='unique_project_file_for_language',
        ),
        migrations.RemoveConstraint(
            model_name='fsttyperelation',
            name='unique_project_file_for_type',
        ),
        migrations.AddConstraint(
            model_name='fstlanguagerelation',
            constraint=models.UniqueConstraint(fields=('fst_file',), name='unique_fst_file_for_lang'),
        ),
        migrations.AddConstraint(
            model_name='fsttyperelation',
            constraint=models.UniqueConstraint(fields=('fst_file',), name='unique_fst_file_for_type'),
        ),
    ]
