# Generated by Django 5.2.1 on 2026-01-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_fstlanguagerelation_unique_project_file_for_language_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fstlanguagerelation',
            name='unique_fst_file_for_lang',
        ),
        migrations.RemoveConstraint(
            model_name='fsttyperelation',
            name='unique_fst_file_for_type',
        ),
        migrations.AddConstraint(
            model_name='fstlanguagerelation',
            constraint=models.UniqueConstraint(fields=('fst_file', 'language'), name='unique_fst_file_for_lang'),
        ),
        migrations.AddConstraint(
            model_name='fsttyperelation',
            constraint=models.UniqueConstraint(fields=('fst_file', 'type'), name='unique_fst_file_for_type'),
        ),
    ]
