# Generated by Django 5.2.1 on 2025-06-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fstproject',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fstproject',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
